### ISSUE TITLE
Record version 3.3 behavior change (breaks ZSQLMethods)

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Record#1]
When I run the Products.ZSQLMethods unit tests under Python 2.7 with the Record egg pinned at 3.2. the tests run through without a problem.

If I move the pin to Record 3.3 I am seeing the following tracebacks:

Error in test test_tuples (Shared.DC.ZRDB.tests.test_results.TestResults)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/jens/src/ZSQL/src/Shared/DC/ZRDB/tests/test_results.py", line 81, in test_tuples
    tuples = ob.tuples()
  File "/Users/jens/src/ZSQL/src/Shared/DC/ZRDB/Results.py", line 108, in tuples
    return map(tuple, self)
  File "/Users/jens/src/ZSQL/src/Shared/DC/ZRDB/Results.py", line 101, in __getitem__
    fields=self._class(self._data[index], parent)
TypeError: unbound method __new__() must be called with r instance as first argument (got ExtensionClass instance instead)

Here's the code triggering the traceback:

https://github.com/zopefoundation/Products.ZSQLMethods/blob/master/src/Shared/DC/ZRDB/Results.py#L101

Here's where the involved `self._class` is set up with many contortions inside `__init__`, possibly all wrong nowadays:

https://github.com/zopefoundation/Products.ZSQLMethods/blob/master/src/Shared/DC/ZRDB/Results.py#L65

**Comment by dataflake** [comment]
Closed by zopefoundation/Products.ZSQLMethods#2
