### ISSUE TITLE
__init__ behavior under Python 3

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Record#2]
In the course of making Products.ZSQLMethods Python 3-compatible I am seeing changed behavior from Python 2 to Python 3. There's two places in the code that call the Record class `__init__` method directly inside a subclass:

https://github.com/zopefoundation/Products.ZSQLMethods/blob/master/src/Shared/DC/ZRDB/Results.py#L82

https://github.com/zopefoundation/Products.ZSQLMethods/blob/master/src/Shared/DC/ZRDB/RDB.py#L148

Those invocations work under Python 2.7 (with Record 3.2, Record 3.3 throws a different error), but under Python 3 they produce the following traceback, regardless of Record egg version (3.2 and 3.3 tested):

Error in test test_results (Shared.DC.ZRDB.tests.testResult.TestResults)
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 601, in run
    testMethod()
  File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/tests/testResult.py", line 23, in test_results
    row = r[0]
  File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/Results.py", line 101, in __getitem__
    fields=self._class(self._data[index], parent)
  File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/Results.py", line 82, in __init__
    Record.__init__(self,data)
TypeError: object.__init__() takes no parameters

**Comment by tseaver** [comment]
I'm pretty sure this is an issue in `Products.ZSQLMethod`:  it should be using `super(r, self).__init__(data)`.

**Comment by dataflake** [comment]
That's what I tried first, but `r` is not visible in that scope.

**Comment by dataflake** [comment]
Corection: The traceback remains the same:

    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 601, in run
        testMethod()
      File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/tests/test_results.py", line 81, in test_tuples
        tuples = ob.tuples()
      File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/Results.py", line 109, in tuples
        return list(map(tuple, self))
      File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/Results.py", line 102, in __getitem__
        fields=self._class(self._data[index], parent)
      File "/Users/jens/src/Products.ZSQLMethods/src/Shared/DC/ZRDB/Results.py", line 82, in __init__
        super(r, self).__init__(data)
    TypeError: object.__init__() takes no parameters

**Comment by dataflake** [comment]
Closed by zopefoundation/Products.ZSQLMethods#2
